import { describe, expect, it } from "vite-plus/test";
import { z } from "zod";
import { generateCompiledFileContent, resolveOutputPath } from "#src/cli/emitter.js";
import { expectParses } from "../expect-parses.js";
import type { CodeGenResult } from "#src/core/codegen/index.js";
import { compileSchemas } from "#src/core/pipeline.js";

describe("generateCompiledFileContent()", () => {
  it("generates a valid compiled file with header and __zcMkv wrapper", () => {
    const result: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef:
        'function safeParse_test(input){\nvar __issues=[];\nif(typeof input!=="string"){__issues.push({code:"invalid_type",expected:"string",received:typeof input,path:[],message:"Expected string"});}\nif(__issues.length>0)return{success:false,error:{issues:__issues}};\nreturn{success:true,data:input};\n}',
      refCount: 0,
      usedHelpers: new Set(),
    };

    const content = generateCompiledFileContent(
      [{ exportName: "validateTest", codegenResult: result, refEntries: [] }],
      "./test.ts",
    );
    expectParses(content);

    expect(content).toContain("// AUTO-GENERATED by zod-compiler");
    expect(content).toContain("// Source: ./test.ts");
    expect(content).toContain("function safeParse_test(input)");
    // Uses __zcMkv factory for Zod compatibility (installs methods on the source schema)
    expect(content).toMatch(
      /__zcMkv\(safeParse_test,\(\(__src_validateTest as any\)\.schema \?\? __src_validateTest\),(?:__fc_\d+|null),(?:__fc_\d+|null)\)/,
    );
    // Imports source schema (needed for zodCompat)
    expect(content).toContain('import { validateTest as __src_validateTest } from "./test"');
  });

  it("resolves __rf[] bases on a plain exported schema, not only a compile() facade", () => {
    // Auto-discovery (the default) exports raw Zod schemas, which have no
    // `.schema` self-reference — reading it alone made every ref base
    // `undefined._zod`, a TypeError thrown while the module was still loading.
    const result: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef: "function safeParse_test(input){\nreturn{success:true,data:input};\n}",
      refCount: 1,
      usedHelpers: new Set(),
    };
    const content = generateCompiledFileContent(
      [
        {
          exportName: "validateTest",
          codegenResult: result,
          refEntries: [{ schema: {}, accessPath: "._zod.def.checks[0]._zod.def.fn" }],
        },
      ],
      "./test.ts",
    );
    expectParses(content);
    expect(content).toContain(
      "var __zs=((__src_validateTest as any).schema ?? __src_validateTest);",
    );
    expect(content).toContain("var __rf=[__zs._zod.def.checks[0]._zod.def.fn];");
  });

  it("imports the source schema for a compact export with no refs of its own", () => {
    // Compact delegation reads the `__zs` binding rather than an `__rf` slot,
    // so refEntries is empty — but generateIIFE still binds `__zs`, and handing
    // it an empty expression would emit `var __zs=;`. Pinned under
    // zodCompat:false, the one combination where the import is not implied.
    const { schemas } = compileSchemas(
      [{ exportName: "Compact", schema: z.object({ name: z.string().min(1) }) }],
      { mode: "inline", compact: true },
    );
    expect(schemas[0]?.refEntries).toHaveLength(0);

    const content = generateCompiledFileContent(schemas, "./compact.ts", { zodCompat: false });
    expectParses(content);

    expect(content).toContain('import { Compact as __src_Compact } from "./compact"');
    expect(content).toContain("var __zs=((__src_Compact as any).schema ?? __src_Compact);");
  });

  it("generates multiple schemas in one file", () => {
    const result1: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef: "function safeParse_a(input){\nreturn{success:true,data:input};\n}",
      refCount: 0,
      usedHelpers: new Set(),
    };
    const result2: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef: "function safeParse_b(input){\nreturn{success:true,data:input};\n}",
      refCount: 0,
      usedHelpers: new Set(),
    };

    const content = generateCompiledFileContent(
      [
        { exportName: "validateA", codegenResult: result1, refEntries: [] },
        { exportName: "validateB", codegenResult: result2, refEntries: [] },
      ],
      "./multi.ts",
    );
    expectParses(content);

    expect(content).toContain("export const validateA");
    expect(content).toContain("export const validateB");
    expect(content).toContain("__zcMkv(safeParse_a,");
    expect(content).toContain("__zcMkv(safeParse_b,");
  });

  it("emits a shared Set block once for repeated enum validators", () => {
    const values = ["one", "two", "three", "four", "five", "six"] as const;
    const { schemas, shared } = compileSchemas(
      [
        { exportName: "A", schema: z.enum(values) },
        { exportName: "B", schema: z.enum(values) },
      ],
      { mode: "inline" },
    );
    const content = generateCompiledFileContent(schemas, "./enums.ts", {
      sharedCode: shared.code,
    });
    expectParses(content);

    expect((content.match(/new Set\(/g) ?? []).length).toBe(1);
    expect((content.match(/var __zcSet_0=/g) ?? []).length).toBe(1);
    expect((content.match(/__zcSet_0\.has\(/g) ?? []).length).toBeGreaterThan(1);
  });

  it("includes zod config import and __zcMsg inside IIFE", () => {
    const result: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef: "function safeParse_test(input){\nreturn{success:true,data:input};\n}",
      refCount: 0,
      usedHelpers: new Set(),
    };

    const content = generateCompiledFileContent(
      [{ exportName: "validateTest", codegenResult: result, refEntries: [] }],
      "./test.ts",
    );
    expectParses(content);

    expect(content).toContain(
      'import { config as __zodCompilerConfig, core as __zcCore, ZodRealError as __zcZodError } from "zod"',
    );
    // __zcMsg, __zcMkv, __zcFin are declared at file level (once per file).
    // __zcMsg reads the config PER CALL — a snapshot would miss a `z.config()`
    // that runs after this module is imported, and dropped `customError`.
    expect(content).toContain("var __zcMsg=function(iss){var c=__zodCompilerConfig()");
    expect(content).toContain("c.customError");
    expect(content).toContain("c.localeError");
    expect(content).toContain("function __zcMkv(fn,schema,fc,is)");
    expect(content).toContain("function __zcFin(e,d)");
  });

  it("always imports source schemas for zodCompat", () => {
    const result: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef: "function safeParse_test(input){\nreturn{success:true,data:input};\n}",
      refCount: 0,
      usedHelpers: new Set(),
    };

    const content = generateCompiledFileContent(
      [{ exportName: "validateTest", codegenResult: result, refEntries: [] }],
      "./test.ts",
    );
    expectParses(content);

    // Source schemas are always imported now (for zodCompat)
    expect(content).toContain('import { validateTest as __src_validateTest } from "./test"');
  });
});

describe("generateCompiledFileContent() — zodCompat: false", () => {
  it("omits source import when no refEntries (enables tree-shaking)", () => {
    const result: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef: "function safeParse_test(input){\nreturn{success:true,data:input};\n}",
      refCount: 0,
      usedHelpers: new Set(),
    };

    const content = generateCompiledFileContent(
      [{ exportName: "validateTest", codegenResult: result, refEntries: [] }],
      "./test.ts",
      { zodCompat: false },
    );
    expectParses(content);

    expect(content).not.toContain("__src_validateTest");
    expect(content).not.toContain('from "./test"');
  });

  it("still imports source schemas when fallbacks exist", () => {
    const result: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef:
        "function safeParse_test(input){\nvar __issues=[];\nreturn{success:true,data:input};\n}",
      refCount: 1,
      usedHelpers: new Set(),
    };

    const content = generateCompiledFileContent(
      [
        {
          exportName: "validateUser",
          codegenResult: result,
          refEntries: [{ schema: {}, accessPath: '.shape["slug"]' }],
        },
      ],
      "./schemas.ts",
      { zodCompat: false },
    );
    expectParses(content);

    expect(content).toContain('import { validateUser as __src_validateUser } from "./schemas"');
    expect(content).toContain("export const validateUser = /* @__PURE__ */");
    expect(content).toMatch(/__zcMkv\(safeParse_test,null,(?:__fc_\d+|null),(?:__fc_\d+|null)\)/);
  });
});

describe("resolveOutputPath()", () => {
  it("defaults to .compiled.ts when no output flag", () => {
    const result = resolveOutputPath("src/schemas.ts", undefined);
    expect(result).toBe("src/schemas.compiled.ts");
  });

  it("uses output flag as-is when it's a file path", () => {
    const result = resolveOutputPath("src/schemas.ts", "out/validators.ts");
    expect(result).toBe("out/validators.ts");
  });

  it("puts compiled file inside directory when output ends with /", () => {
    const result = resolveOutputPath("src/schemas.ts", "out/");
    expect(result).toContain("out/");
    expect(result).toContain("schemas.compiled.ts");
  });
});
