packages:
  - "apps/*"
  - "benchmarks"

catalog:
  "@types/node": ^25.9.1
  tsx: ^4.22.4
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vitest: 4.1.10
  zod: ^4.5.2
  vite-plus: 0.2.6
  "@vitest/coverage-v8": 4.1.10
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
